version: 2

sources:
  - name: googles_analytics_4
    schema: google_analytics_4
    tables:
      - name: events_20210131
      
  - name: google_sheets
    schema: google_sheets
    tables:
      - name: account_manager_region_mapping

  - name: sales_database
    schema: sales_database
    tables:
      - name: feedback
      - name: payment
      - name: product
      - name: order
      - name: order_item
      - name: seller
      - name: user

  - name: Local_bike
    schema: Local_bike
    tables:
      - name: brands
      - name: categories
      - name: customers
      - name: order_items
      - name: orders
      - name: products
      - name: staffs
      - name: stocks
      - name: stores